Lohan home page and event page student
wlim0053/SEMS_2023 pull request #2
Opened 2023-05-01 09:57 UTC by lohzn

2023-05-01 10:50 UTC, wlim0053 requested changes
Please read on the comments and provide ur feedback. thanks!

2023-05-01 10:50 UTC, wlim0053 commented on frontend/src/components/Calendar.tsx
> +  }, []);
It this used for handling the mobile view?

2023-05-01 10:50 UTC, wlim0053 commented on frontend/src/components/CountdownTimer.tsx
> +  const p = isSmallerThan500 ? "0.1rem" : { base: "1rem", md: "1.5rem" };
look up on chakra ui 
https://chakra-ui.com/docs/styled-system/responsive-styles
i think if u configure these it should automatically detect the screen sizes and u don't have to manually type these each time

2023-05-01 10:50 UTC, wlim0053 commented on frontend/src/components/EventPage.tsx
> +  }, []);
u might wanna take a look at this
https://www.youtube.com/watch?v=QQYeipc_cik&ab_channel=LamaDev

the useEffect might lead to some memory leakage, so make sure the useEffect only triggers when necessary

2023-05-01 14:56 UTC, lohzn commented on frontend/src/components/Calendar.tsx
> +  }, []);
Yes, when the window size is less than or equal to 500px, it will set the state of isMobile accordingly.

2023-05-01 15:00 UTC, lohzn commented on frontend/src/components/CountdownTimer.tsx
> +  const p = isSmallerThan500 ? "0.1rem" : { base: "1rem", md: "1.5rem" };
I will take a look at it and try to adjust the code, to avoid having to manually type each time.

2023-05-01 15:03 UTC, lohzn commented on frontend/src/components/EventPage.tsx
> +  }, []);
Thanks for the link. I'll check my code and make sure to optimize the useEffect hook to avoid possible memory leakage.

2023-05-15 00:09 UTC, lohzn commented on frontend/src/components/CountdownTimer.tsx
> +  const p = isSmallerThan500 ? "0.1rem" : { base: "1rem", md: "1.5rem" };
Addressed

2023-05-15 00:09 UTC, lohzn commented on frontend/src/components/EventPage.tsx
> +  }, []);
Addressed

2023-05-16 06:32 UTC, wlim0053 approved these changes

2023-05-16 06:32 UTC, merged